/**
 * Help Center — in-app FAQ + troubleshooting reference.
 *
 * Linked from Profile tab → "Help Center" → `/help`. Self-contained:
 * no API calls, no state — content baked into the bundle so it works
 * offline, even on dial-up. Mirrors the layout of /privacy, /terms,
 * /data-privacy so the user encounters one consistent legal-doc /
 * support surface.
 *
 * Each FAQ is a heading + body block. The bottom of the screen has a
 * tappable mail-to link routing to sacredquest2@gmail.com so the user
 * can escalate when the FAQ doesn't answer their question.
 *
 * Crisis callout sits at the very top — non-negotiable for a wellness
 * surface. It points to local emergency services + a couple of
 * widely-recognised crisis lines without trying to be exhaustive
 * (different countries, different numbers — we don't fake authority).
 */

import React from 'react';
import { Linking, Pressable, StyleSheet, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Screen, GoldenHeader, SacredCard } from '@kiaanverse/ui';
import { Text } from 'react-native';

const GOLD = '#D4A017';
const SACRED_WHITE = '#F0EBE1';
const TEXT_MUTED = 'rgba(240,235,225,0.62)';
const CRISIS_RED = '#dc2626';

interface FAQ {
  readonly heading: string;
  readonly body: string;
}

const FAQS: readonly FAQ[] = [
  {
    heading: 'How is my journal kept private?',
    body:
      'Every Sacred Reflection is sealed on your device with AES-256-GCM ' +
      'before it ever leaves it. The server only stores ciphertext plus ' +
      'plaintext metadata you choose (mood, tags, timestamp). Even our ' +
      'engineers cannot read your reflections.',
  },
  {
    heading: 'How does Sakha know what to say?',
    body:
      'Sakha’s replies are generated by a guided AI that retrieves ' +
      'verses, commentaries, and stories from a curated Bhagavad Gita ' +
      'corpus before answering. When the model isn’t confident the ' +
      'answer is faithful to the source, Sakha says so rather than ' +
      'guessing. Insights are reflective — not therapy or medical ' +
      'advice.',
  },
  {
    heading: 'The microphone won’t turn on for voice chat',
    body:
      'On Android, open Settings → Apps → Kiaanverse → ' +
      'Permissions → Microphone and choose "Allow only while using ' +
      'the app". Then re-enter the Voice Companion screen. If voice still ' +
      'doesn’t start, restart the app once — a fresh foreground ' +
      'service is required after permission changes.',
  },
  {
    heading: '"Hey Sakha" doesn’t wake the app',
    body:
      'The wake-word listener is opt-in. Long-press the floating lotus ' +
      'button on any home screen, then confirm "Turn on Hey Sakha" in the ' +
      'dialog. The listener only runs when the screen you’re on ' +
      'allows ambient voice (it stays silent on auth, onboarding, and ' +
      'inside the Voice Companion itself, which has its own session).',
  },
  {
    heading: 'I’m in crisis right now',
    body:
      'Please reach out to someone trained to help. In India, dial iCall ' +
      'on +91-9152987821 or AASRA on +91-9820466726. In the US, dial or ' +
      'text 988. In the UK, dial 116 123. For any country, your local ' +
      'emergency number works. Sakha is reflective, not a replacement for ' +
      'a real human in crisis.',
  },
  {
    heading: 'How do I delete my account or my data?',
    body:
      'Profile → Account → Edit Profile → scroll to the ' +
      'bottom for Delete Account. Encrypted journal data is permanently ' +
      'removed within 30 days. You can also export everything we hold for ' +
      'you (JSON + ciphertext bundle) before deleting — see Profile ' +
      '→ Data & Privacy.',
  },
  {
    heading: 'I was charged but my subscription didn’t activate',
    body:
      'Subscriptions are processed by Google Play (Android) or the App ' +
      'Store (iOS). If the charge cleared but the app still shows the ' +
      'free tier, force-close and re-open the app once — the ' +
      'receipt usually re-validates within 60 seconds. If it persists, ' +
      'send us your order ID (visible in the store receipt) and we will ' +
      'restore the entitlement.',
  },
  {
    heading: 'Can I use Kiaanverse offline?',
    body:
      'Most of the app works offline: your journal, journey progress, ' +
      'verse library, and saved reflections all live on the device. ' +
      'Sakha’s real-time voice responses and KIAAN’s wisdom ' +
      'lookups need a connection — we’ll show a clear "offline" ' +
      'banner when something can’t reach the server.',
  },
  {
    heading: 'Which languages does Sakha speak?',
    body:
      'Sakha speaks fluently in English and Hindi today, with verse ' +
      'recitation also available in Sanskrit. We’re actively ' +
      'expanding to additional Indian languages — check the ' +
      'in-app Language settings (Profile → Account → Language) ' +
      'for the latest list.',
  },
  {
    heading: 'How do I report a bug or suggest a feature?',
    body:
      'Use the Contact Us card below or write directly to ' +
      'sacredquest2@gmail.com. A short description plus a screenshot or ' +
      'screen-recording helps us reproduce the issue much faster.',
  },
];

export default function HelpCenterScreen(): React.JSX.Element {
  const router = useRouter();

  const openMail = (): void => {
    void Linking.openURL(
      'mailto:sacredquest2@gmail.com?subject=Kiaanverse%20Support',
    );
  };

  return (
    <Screen scroll gradient gradientVariant="cosmic">
      <GoldenHeader title="Help Center" onBack={() => router.back()} />

      <SacredCard style={[styles.card, styles.crisisCard]}>
        <Text style={[styles.eyebrow, styles.crisisEyebrow]}>
          IF YOU ARE IN CRISIS
        </Text>
        <Text style={styles.crisisBody}>
          Please reach a real human now. India: iCall +91-9152987821. US:
          dial or text 988. UK: 116 123. Or your local emergency number.
          Sakha is here for reflection — not for a moment that needs
          immediate human help.
        </Text>
      </SacredCard>

      <SacredCard style={styles.card}>
        <Text style={styles.eyebrow}>FREQUENTLY ASKED</Text>
        <Text style={styles.lastUpdated}>Last Updated: May 2026</Text>

        <View style={styles.sections}>
          {FAQS.map((faq) => (
            <View key={faq.heading} style={styles.section}>
              <Text style={styles.heading}>{faq.heading}</Text>
              <Text style={styles.body}>{faq.body}</Text>
            </View>
          ))}

          <Pressable
            onPress={openMail}
            accessibilityRole="link"
            accessibilityLabel="Email sacredquest2@gmail.com"
            style={styles.contactRow}
          >
            <Text style={styles.contactLabel}>
              Still stuck? Write to us at
            </Text>
            <Text style={styles.contactEmail}>sacredquest2@gmail.com</Text>
            <Text style={styles.contactSla}>
              We answer within 7 business days.
            </Text>
          </Pressable>
        </View>
      </SacredCard>
    </Screen>
  );
}

const styles = StyleSheet.create({
  card: {
    marginTop: 12,
    paddingHorizontal: 20,
    paddingVertical: 24,
  },
  crisisCard: {
    borderLeftWidth: 3,
    borderLeftColor: CRISIS_RED,
  },
  eyebrow: {
    fontFamily: 'Outfit-SemiBold',
    fontSize: 11,
    letterSpacing: 1.4,
    color: GOLD,
    textTransform: 'uppercase',
  },
  crisisEyebrow: {
    color: CRISIS_RED,
  },
  crisisBody: {
    fontFamily: 'CrimsonText-Regular',
    fontSize: 15,
    lineHeight: 24,
    color: SACRED_WHITE,
    marginTop: 10,
  },
  lastUpdated: {
    fontFamily: 'CrimsonText-Italic',
    fontSize: 13,
    color: TEXT_MUTED,
    marginTop: 4,
    marginBottom: 20,
  },
  sections: {
    gap: 18,
  },
  section: {
    gap: 6,
  },
  heading: {
    fontFamily: 'Outfit-SemiBold',
    fontSize: 15,
    color: SACRED_WHITE,
  },
  body: {
    fontFamily: 'CrimsonText-Regular',
    fontSize: 15,
    lineHeight: 24,
    color: 'rgba(240,235,225,0.85)',
  },
  contactRow: {
    marginTop: 8,
    paddingTop: 18,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(212,160,23,0.35)',
    gap: 4,
  },
  contactLabel: {
    fontFamily: 'CrimsonText-Italic',
    fontSize: 13,
    color: TEXT_MUTED,
  },
  contactEmail: {
    fontFamily: 'Outfit-SemiBold',
    fontSize: 15,
    color: GOLD,
  },
  contactSla: {
    fontFamily: 'CrimsonText-Italic',
    fontSize: 12,
    color: TEXT_MUTED,
    marginTop: 2,
  },
});
