/**
 * Terms of Service — readable terms text rendered inside the app.
 *
 * Linked from Profile tab → "Terms of Service" → `/(app)/terms`.
 * Self-contained: no API calls, no state — content baked into the
 * bundle so it's available offline. Mirrors PrivacyPolicyScreen so
 * users see one consistent legal-doc surface.
 */

import React from 'react';
import { StyleSheet, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Screen, GoldenHeader, SacredCard } from '@kiaanverse/ui';
import { Text } from 'react-native';

const GOLD = '#D4A017';
const SACRED_WHITE = '#F0EBE1';
const TEXT_MUTED = 'rgba(240,235,225,0.62)';

interface Section {
  readonly heading: string;
  readonly body: string;
}

const SECTIONS: readonly Section[] = [
  {
    heading: '1. Agreement to Terms',
    body:
      'By accessing or using Kiaanverse / MindVibe ("the Service"), you ' +
      'agree to be bound by these Terms of Service. If you disagree with ' +
      'any part of these Terms, please do not use the Service.',
  },
  {
    heading: '2. Wellness, Not Medical Advice',
    body:
      'Kiaanverse is a personal wellness companion grounded in Bhagavad ' +
      'Gita wisdom. It is NOT medical software and is NOT a substitute ' +
      'for professional medical, psychiatric, or psychological advice. ' +
      'Always consult qualified healthcare professionals for medical ' +
      'decisions. If you are in crisis, contact local emergency services ' +
      'or a crisis line immediately.',
  },
  {
    heading: '3. Account Eligibility',
    body:
      '• You must be at least 13 years of age to use the Service.\n' +
      '• You agree to provide accurate registration information.\n' +
      '• You are responsible for keeping your password and device safe.\n' +
      '• Notify us immediately of any unauthorized access to your account.',
  },
  {
    heading: '4. Your Content',
    body:
      'You retain ownership of every reflection, verse note, and journal ' +
      'entry you create. Your encrypted journal content is sealed on your ' +
      'device with AES-256-GCM before it ever leaves it — Kiaanverse ' +
      'cannot read it. You grant us only the limited rights needed to ' +
      'operate the Service (storage, sync, backup).',
  },
  {
    heading: '5. Acceptable Use',
    body:
      'You agree not to:\n' +
      '• Use the Service to harass, threaten, or harm any person.\n' +
      '• Attempt to access another user’s account or data.\n' +
      '• Reverse-engineer, scrape, or disrupt the Service.\n' +
      '• Misrepresent Bhagavad Gita teachings or our content.',
  },
  {
    heading: '6. Subscriptions & Payments',
    body:
      'Premium tiers (where available) are billed through Google Play, ' +
      'the App Store, or Stripe. Subscriptions auto-renew until cancelled ' +
      'in the relevant store. Refunds follow the policy of the platform ' +
      'where you subscribed.',
  },
  {
    heading: '7. AI & Sakha (KIAAN Voice Companion)',
    body:
      'Sakha’s guidance is generated by AI and curated against the ' +
      'Bhagavad Gita corpus. Insights are reflective and educational — ' +
      'they are not a substitute for therapy, counselling, or medical ' +
      'care. We continuously refine the model but do not warrant its ' +
      'output for any specific outcome.',
  },
  {
    heading: '8. Termination',
    body:
      'You may delete your account at any time from Settings → ' +
      'Account. We may suspend or terminate accounts that violate these ' +
      'Terms or threaten the safety of other seekers. On deletion, your ' +
      'encrypted content is permanently removed within 30 days, except ' +
      'where retention is required by law.',
  },
  {
    heading: '9. Disclaimers & Limitation of Liability',
    body:
      'The Service is provided "as is" without warranties of any kind. ' +
      'To the fullest extent permitted by law, Kiaanverse and its ' +
      'creators are not liable for indirect, incidental, or consequential ' +
      'damages arising from your use of the Service.',
  },
  {
    heading: '10. Changes to These Terms',
    body:
      'We may update these Terms to reflect changes in the Service or ' +
      'the law. Material changes will be announced in-app at least 14 ' +
      'days before they take effect. Continued use after the effective ' +
      'date constitutes acceptance.',
  },
  {
    heading: '11. Governing Law',
    body:
      'These Terms are governed by the laws applicable to your country of ' +
      'residence to the extent required by mandatory consumer-protection ' +
      'rules. Any disputes will first be addressed in good faith through ' +
      'direct correspondence with the contact email below.',
  },
  {
    heading: '12. Contact',
    body:
      'For questions about these Terms, account or billing issues, or to ' +
      'report a violation, write to us at:\n\nsacredquest2@gmail.com\n\n' +
      'We answer every legal / support email within 7 business days.',
  },
];

export default function TermsOfServiceScreen(): React.JSX.Element {
  const router = useRouter();

  return (
    <Screen scroll gradient gradientVariant="cosmic">
      <GoldenHeader title="Terms of Service" onBack={() => router.back()} />

      <SacredCard style={styles.card}>
        <Text style={styles.eyebrow}>KIAANVERSE TERMS OF SERVICE</Text>
        <Text style={styles.lastUpdated}>Last Updated: May 2026</Text>

        <View style={styles.sections}>
          {SECTIONS.map((s) => (
            <View key={s.heading} style={styles.section}>
              <Text style={styles.heading}>{s.heading}</Text>
              <Text style={styles.body}>{s.body}</Text>
            </View>
          ))}
        </View>
      </SacredCard>
    </Screen>
  );
}

const styles = StyleSheet.create({
  card: {
    marginTop: 12,
    paddingHorizontal: 20,
    paddingVertical: 24,
  },
  eyebrow: {
    fontFamily: 'Outfit-SemiBold',
    fontSize: 11,
    letterSpacing: 1.4,
    color: GOLD,
    textTransform: 'uppercase',
  },
  lastUpdated: {
    fontFamily: 'CrimsonText-Italic',
    fontSize: 13,
    color: TEXT_MUTED,
    marginTop: 4,
    marginBottom: 20,
  },
  sections: {
    gap: 18,
  },
  section: {
    gap: 6,
  },
  heading: {
    fontFamily: 'Outfit-SemiBold',
    fontSize: 15,
    color: SACRED_WHITE,
  },
  body: {
    fontFamily: 'CrimsonText-Regular',
    fontSize: 15,
    lineHeight: 24,
    color: 'rgba(240,235,225,0.85)',
  },
});
