app = "aadi-api"
primary_region = "fra"
[build]
  dockerfile = "Dockerfile"
[env]
  PORT = "8000"
[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
