# Aider configuration file
# See: https://aider.chat/docs/config.html

# Model configuration
model: gpt-4

# Git settings
auto-commits: false
dirty-commits: false

# Code style
pretty: true

# Suggestions and prompts
prompts:
  code-review: |
    You are a code reviewer for the MindVibe project, a privacy-first mental health app.
    
    Review the code changes and provide constructive feedback on:
    1. Security concerns (especially around JWT, EdDSA keys, and private data handling)
    2. Code quality and best practices
    3. Potential bugs or edge cases
    4. Performance considerations
    5. Documentation completeness
    6. Testing coverage
    
    Key policies to enforce:
    - Never commit private key files (only *-pub.json files from keyset_eddsa/)
    - Follow existing code style and conventions
    - Ensure proper error handling
    - Maintain backwards compatibility where possible
    
    Provide specific, actionable suggestions with code examples when appropriate.
    Keep feedback concise and prioritize the most important issues.
