/**
 * @kiaanverse/api — API client, typed endpoints, error classes, and query client
 */

// Client
export {
  apiClient,
  setTokenManager,
  getCurrentAccessToken,
  refreshAccessToken,
} from './client';
export { api } from './endpoints';
export { API_CONFIG } from './config';

// Unified KIAAN surface — `/api/kiaan/*` endpoints (see kiaan/client.ts).
export {
  kiaan,
  type KiaanClient,
  type KiaanMessage,
  type KiaanGitaVerse,
  type KiaanChatRequest,
  type KiaanChatResponse,
  type KiaanToolRequest,
  type EmotionalResetInputs as KiaanEmotionalResetInputs,
  type ArdhaInputs as KiaanArdhaInputs,
  type ViyogaInputs as KiaanViyogaInputs,
  type KarmaResetInputs as KiaanKarmaResetInputs,
  type RelationshipCompassInputs as KiaanRelationshipCompassInputs,
  type KarmaLytixMetadata as KiaanKarmaLytixMetadata,
  useKiaanRoomChat,
  useKiaanVoice,
  type KiaanRoomChatMessage,
  type UseKiaanRoomChatResult,
  type UseKiaanVoiceResult,
} from './kiaan';

// Error classes and type guards
export {
  ApiError,
  AuthError,
  OfflineError,
  ValidationError,
  isApiError,
  isAuthError,
  isOfflineError,
  isValidationError,
} from './errors';
export type { AuthErrorCode } from './errors';

// Auth service
export { authService } from './auth/authService';
export type { RegisterData, LoginResult } from './auth/authService';

// Query client
export { createAppQueryClient, createAppPersister } from './queryClient';

// Gita verse cache (offline-first)
export { gitaCache } from './cache/gitaCache';

// Ardha — response parser + canonical pillar metadata (shared with UI)
export {
  parseArdhaResponse,
  humaniseEmotion,
  ARDHA_SECTIONS,
  ARDHA_SECTION_KEYS,
  type ArdhaSectionKey,
  type ArdhaSectionMeta,
  type ParsedArdhaSection,
} from './ardha/parser';

// Subscription (4-tier: free/bhakta/sadhak/siddha)
// NOTE: The lowercase 'SubscriptionTier' from constants.ts is exposed here as
// 'SubscriptionPlanId' to avoid colliding with the uppercase
// 'SubscriptionTier' from ./types that the User interface uses.
export {
  type SubscriptionTier as SubscriptionPlanId,
  type BillingPeriod,
  type TierConfig,
  TIER_CONFIGS,
  TIER_RANK,
  IAP_PRODUCT_IDS,
  ALL_PRODUCT_IDS,
  KIAAN_MONTHLY_QUOTA,
  WISDOM_JOURNEY_LIMITS,
  initializeIAP,
  disconnectIAP,
  getProducts,
  purchaseSubscription,
  restorePurchases,
  verifyReceipt,
  setIapAccountTag,
  openManageSubscription,
  IAPError,
  isSubscriptionUnavailableError,
  type IAPProduct,
  type PurchaseResult,
} from './subscription';

// Types (SubscriptionTier already exported from ./subscription above)
export type {
  User,
  AuthTokens,
  AuthResponse,
  ProfileResponse,
  LoginResponse,
  SignupResponse,
  MeResponse,
  RefreshResponse,
  GitaVerse,
  GitaChapter,
  GitaVerseDetail,
  GitaVerseReference,
  GitaVerseResponse,
  GitaVerseSummary,
  GitaChapterDetail,
  GitaSearchResult,
  GitaSearchResponse,
  GitaTranslationSet,
  SpiritualMood,
  MoodEntry,
  MoodCreatePayload,
  MoodInsight,
  KarmaNodeData,
  KarmaTreeLevel,
  KarmaTreeResponse,
  JourneyStepType,
  JourneyDifficulty,
  JourneyCategory,
  WisdomJourneyStep,
  WisdomJourneyDetail,
  JourneyModernExample,
  JourneyPracticeBlock,
  DashboardData,
  DashboardTodayStep,
  EnemyMasteryProgress,
  JourneyDifficultyLevel,
  StepCompletionResult,
  UserJourneyProgress,
  Journey,
  JourneyStep,
  JourneyTemplate,
  JourneyStatus,
  SyncStatus,
  SyncQueueItem,
  TokenManager,
  EmotionalResetStep,
  EmotionalResetSession,
  EmotionalResetStepData,
  EmotionalResetStepResponse,
  EmotionalResetSummary,
  KarmaResetPhase,
  KarmaResetSession,
  KarmaResetPhaseResponse,
  KarmaResetCompletion,
  CommunityCircle,
  CommunityPost,
  CreatePostPayload,
  WisdomRoom,
  WisdomRoomMessage,
  SadhanaDaily,
  SadhanaRecord,
  SadhanaStreak,
  RelationshipCompassResult,
  RelationshipGuidance,
  KarmaFootprintResult,
  KarmaFootprintAnalysis,
  ViyogaResult,
  ViyogaResponse,
  ArdhaResult,
  ArdhaReframeResponse,
  ArdhaStructuredResponse,
  DeepInsight,
  DeepInsightsSummary,
  GunaBalance,
  EmotionalPattern,
  KarmaLytixWeeklyReport,
  KarmaLytixReflection,
  KarmaLytixGitaEcho,
  KarmaLytixJournalMetadataSummary,
  KarmaLytixComparison,
  MoodTrend,
  WeeklyInsight,
  AnalyticsDashboard,
  MeditationTrack,
  JournalEntry,
  JournalListResponse,
  UserSettings,
} from './types';

// TanStack Query hooks
export {
  queryKeys,
  useProfile,
  useGitaChapters,
  useGitaChapter,
  useGitaVerse,
  useGitaSearch,
  useGitaSearchFull,
  useGitaVerseDetail,
  useGitaTranslations,
  useGitaChapterDetail,
  useJourneyTemplates,
  useJourneys,
  useJourney,
  useJourneyDashboard,
  useWisdomJourneyDetail,
  useJourneyProgress,
  useStartJourney,
  usePauseJourney,
  useResumeJourney,
  useAbandonJourney,
  useCompleteStep,
  useCompleteWisdomStep,
  useCreateMood,
  useKarmaTree,
  useUnlockKarma,
  useSendChatMessage,
  useStartEmotionalReset,
  useEmotionalResetStepData,
  useEmotionalResetStep,
  useCompleteEmotionalReset,
  useCommunityCircles,
  useCommunityPosts,
  useJoinCircle,
  useCreatePost,
  useReactToPost,
  useWisdomRooms,
  useWisdomRoomMessages,
  useSendWisdomRoomMessage,
  useSadhanaDaily,
  useSadhanaStreak,
  useCompleteSadhana,
  useSadhanaHistory,
  useRelationshipCompass,
  useRelationshipGuide,
  useKarmaFootprint,
  useStartKarmaReset,
  useKarmaResetStep,
  useCompleteKarmaReset,
  useViyogaGuide,
  useViyogaChat,
  useArdhaReframe,
  useArdhaStructuredReframe,
  useMeditationTracks,
  useDeepInsights,
  useGunaBalance,
  useEmotionalPatterns,
  useMoodTrends,
  useWeeklyInsights,
  useJournalEntries,
  useJournalEntry,
  useCreateJournal,
  useUpdateJournal,
  useDeleteJournal,
  useKarmaLytixWeeklyReport,
  useGenerateKarmaLytixReport,
  useKarmaLytixHistory,
  useUserSettings,
  useUpdateSettings,
  usePrivacyStatus,
  useRequestExport,
  useRequestDeletion,
  useCancelDeletion,
} from './hooks';

// Bundled Gita corpus (matches kiaanverse.com/m/ — full text for all 700 verses)
export {
  getLocalChapter,
  getLocalChapterHeaders,
  getLocalVerse,
  isLocalGitaAvailable,
} from './localGita';
export type {
  LocalGitaChapter,
  LocalGitaChapterHeader,
  LocalGitaVerse,
} from './localGita';
