/**
 * @kiaanverse/api — API client, typed endpoints, error classes, and query client
 */

// Client
export { apiClient, setTokenManager } from './client';
export { api } from './endpoints';
export { API_CONFIG } from './config';

// Error classes and type guards
export {
  ApiError,
  AuthError,
  OfflineError,
  ValidationError,
  isApiError,
  isAuthError,
  isOfflineError,
  isValidationError,
} from './errors';
export type { AuthErrorCode } from './errors';

// Auth service
export { authService } from './auth/authService';
export type { RegisterData, LoginResult } from './auth/authService';

// Query client
export { createAppQueryClient, createAppPersister } from './queryClient';

// Gita verse cache (offline-first)
export { gitaCache } from './cache/gitaCache';

// Subscription (4-tier: free/bhakta/sadhak/siddha)
export {
  type SubscriptionTier as VibePlayerTier,
  type SubscriptionTier,
  type BillingPeriod,
  type TierConfig,
  TIER_CONFIGS,
  TIER_RANK,
  IAP_PRODUCT_IDS,
  ALL_PRODUCT_IDS,
  KIAAN_MONTHLY_QUOTA,
  WISDOM_JOURNEY_LIMITS,
  initializeIAP,
  disconnectIAP,
  getProducts,
  purchaseSubscription,
  restorePurchases,
  verifyReceipt,
  IAPError,
  type IAPProduct,
  type PurchaseResult,
} from './subscription';

// Types (SubscriptionTier already exported from ./subscription above)
export type {
  User,
  AuthTokens,
  AuthResponse,
  ProfileResponse,
  LoginResponse,
  SignupResponse,
  MeResponse,
  RefreshResponse,
  GitaVerse,
  GitaChapter,
  GitaVerseDetail,
  GitaVerseReference,
  GitaVerseResponse,
  GitaVerseSummary,
  GitaChapterDetail,
  GitaSearchResult,
  GitaSearchResponse,
  GitaTranslationSet,
  SpiritualMood,
  MoodEntry,
  MoodCreatePayload,
  MoodInsight,
  KarmaNodeData,
  KarmaTreeLevel,
  KarmaTreeResponse,
  JourneyStepType,
  JourneyDifficulty,
  JourneyCategory,
  WisdomJourneyStep,
  WisdomJourneyDetail,
  StepCompletionResult,
  UserJourneyProgress,
  Journey,
  JourneyStep,
  JourneyTemplate,
  JourneyStatus,
  SyncStatus,
  SyncQueueItem,
  TokenManager,
  EmotionalResetStep,
  EmotionalResetSession,
  EmotionalResetStepData,
  EmotionalResetStepResponse,
  EmotionalResetSummary,
  KarmaResetPhase,
  KarmaResetSession,
  KarmaResetPhaseResponse,
  KarmaResetCompletion,
  CommunityCircle,
  CommunityPost,
  CreatePostPayload,
  WisdomRoom,
  WisdomRoomMessage,
  SadhanaDaily,
  SadhanaRecord,
  SadhanaStreak,
  RelationshipCompassResult,
  RelationshipGuidance,
  KarmaFootprintResult,
  KarmaFootprintAnalysis,
  ViyogaResult,
  ViyogaResponse,
  ArdhaResult,
  ArdhaReframeResponse,
  DeepInsight,
  DeepInsightsSummary,
  GunaBalance,
  EmotionalPattern,
  MoodTrend,
  WeeklyInsight,
  AnalyticsDashboard,
  MeditationTrack,
  JournalEntry,
  JournalListResponse,
  UserSettings,
} from './types';

// TanStack Query hooks
export {
  queryKeys,
  useProfile,
  useGitaChapters,
  useGitaChapter,
  useGitaVerse,
  useGitaSearch,
  useGitaSearchFull,
  useGitaVerseDetail,
  useGitaTranslations,
  useGitaChapterDetail,
  useJourneyTemplates,
  useJourneys,
  useJourney,
  useJourneyDashboard,
  useWisdomJourneyDetail,
  useJourneyProgress,
  useStartJourney,
  useCompleteStep,
  useCompleteWisdomStep,
  useCreateMood,
  useKarmaTree,
  useUnlockKarma,
  useSendChatMessage,
  useStartEmotionalReset,
  useEmotionalResetStepData,
  useEmotionalResetStep,
  useCompleteEmotionalReset,
  useCommunityCircles,
  useCommunityPosts,
  useJoinCircle,
  useCreatePost,
  useReactToPost,
  useWisdomRooms,
  useWisdomRoomMessages,
  useSendWisdomRoomMessage,
  useSadhanaDaily,
  useSadhanaStreak,
  useCompleteSadhana,
  useSadhanaHistory,
  useRelationshipCompass,
  useRelationshipGuide,
  useKarmaFootprint,
  useStartKarmaReset,
  useKarmaResetStep,
  useCompleteKarmaReset,
  useViyogaGuide,
  useViyogaChat,
  useArdhaReframe,
  useMeditationTracks,
  useDeepInsights,
  useGunaBalance,
  useEmotionalPatterns,
  useMoodTrends,
  useWeeklyInsights,
  useJournalEntries,
  useJournalEntry,
  useCreateJournal,
  useUpdateJournal,
  useDeleteJournal,
  useUserSettings,
  useUpdateSettings,
} from './hooks';
