/**
 * WisdomStep — Bhagavad Gita wisdom card (Step 3 of Emotional Reset).
 *
 * Displays a verse in Sanskrit with its English translation, followed by a
 * personalized "How This Applies" section generated by the API based on
 * the user's selected emotion. The card uses a golden border with inner
 * glow to evoke the sacred nature of the Gita's teachings.
 */

import React from 'react';
import { View, ScrollView, StyleSheet } from 'react-native';
import Animated, { FadeIn, FadeInDown } from 'react-native-reanimated';
import { Text, GoldenButton, GlowCard, MandalaSpin, DivineGradient, colors, spacing, radii } from '@kiaanverse/ui';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface WisdomStepProps {
  readonly stepData: {
    verseRef?: string;
    sanskrit?: string;
    translation?: string;
    application?: string;
    guidance?: string;
  } | null;
  readonly onNext: () => void;
}

// ---------------------------------------------------------------------------
// Fallback content used when the API has not yet returned data
// ---------------------------------------------------------------------------

const FALLBACK = {
  verseRef: 'Bhagavad Gita 2.14',
  sanskrit:
    '\u092E\u093E\u0924\u094D\u0930\u093E\u0938\u094D\u092A\u0930\u094D\u0936\u093E\u0938\u094D\u0924\u0941 \u0915\u094C\u0928\u094D\u0924\u0947\u092F \u0936\u0940\u0924\u094B\u0937\u094D\u0923\u0938\u0941\u0916\u0926\u0941\u0903\u0916\u0926\u093E\u0903',
  translation:
    'The contacts of the senses with their objects, which give rise to the feelings of heat and cold, pleasure and pain, are transient. Bear them patiently.',
  application: 'This too shall pass. Observe the feeling without becoming it.',
};

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function WisdomStep({ stepData, onNext }: WisdomStepProps): React.JSX.Element {
  const verseRef = stepData?.verseRef ?? FALLBACK.verseRef;
  const sanskrit = stepData?.sanskrit ?? FALLBACK.sanskrit;
  const translation = stepData?.translation ?? FALLBACK.translation;
  const application = stepData?.application ?? FALLBACK.application;
  const guidance = stepData?.guidance;

  return (
    <DivineGradient variant="healing">
    <ScrollView
      style={styles.scroll}
      contentContainerStyle={styles.scrollContent}
      showsVerticalScrollIndicator={false}
    >
      <Animated.View entering={FadeIn.duration(500)}>
        <Text variant="h2" color={colors.divine.aura} align="center">
          Sacred Wisdom
        </Text>
        <Text variant="caption" color={colors.text.muted} align="center" style={styles.verseRef}>
          {verseRef}
        </Text>
      </Animated.View>

      {/* Verse card with mandala background and golden glow */}
      <Animated.View entering={FadeInDown.delay(300).duration(600)}>
        <View style={styles.verseCardContainer}>
          <View style={styles.mandalaBackground}>
            <MandalaSpin size={200} speed="slow" opacity={0.1} />
          </View>
          <GlowCard variant="divine">
            <Text
              variant="body"
              color={colors.primary[200]}
              align="center"
              style={styles.sanskritText}
            >
              {sanskrit}
            </Text>
            <View style={styles.divider} />
            <Text variant="body" color={colors.text.secondary} align="center" style={styles.translation}>
              {translation}
            </Text>
          </GlowCard>
        </View>
      </Animated.View>

      {/* Application section */}
      <Animated.View entering={FadeInDown.delay(600).duration(500)}>
        <Text variant="label" color={colors.text.primary} style={styles.sectionTitle}>
          How This Applies
        </Text>
        <Text variant="body" color={colors.text.secondary} style={styles.applicationText}>
          {application}
        </Text>
      </Animated.View>

      {/* Personalized guidance from AI (if available) */}
      {guidance ? (
        <Animated.View entering={FadeInDown.delay(800).duration(500)}>
          <View style={styles.guidanceCard}>
            <Text variant="bodySmall" color={colors.primary[300]}>
              {guidance}
            </Text>
          </View>
        </Animated.View>
      ) : null}

      <GoldenButton
        title="Continue"
        onPress={onNext}
        style={styles.continueButton}
        testID="wisdom-continue-btn"
      />
    </ScrollView>
    </DivineGradient>
  );
}

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const styles = StyleSheet.create({
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingVertical: spacing.lg,
    gap: spacing.lg,
  },
  verseRef: {
    marginTop: spacing.xs,
  },
  verseCardContainer: {
    position: 'relative',
  },
  mandalaBackground: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 0,
  },
  sanskritText: {
    fontStyle: 'italic',
    lineHeight: 28,
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: colors.alpha.goldMedium,
    marginVertical: spacing.md,
  },
  translation: {
    lineHeight: 24,
  },
  sectionTitle: {
    marginBottom: spacing.xs,
  },
  applicationText: {
    lineHeight: 24,
  },
  guidanceCard: {
    backgroundColor: colors.alpha.goldLight,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.alpha.goldMedium,
    padding: spacing.md,
  },
  continueButton: {
    marginTop: spacing.md,
  },
});
