/**
 * KIAAN Vibe Music Player - Constants
 *
 * Gita chapters data and default settings.
 */

import type { GitaChapter, GitaLearningSettings, GitaSoundscape } from './types'

// ============ Gita Chapters ============

export const GITA_CHAPTERS: GitaChapter[] = [
  {
    number: 1,
    nameSanskrit: 'अर्जुनविषादयोग',
    nameEnglish: 'Arjuna Vishada Yoga',
    nameHindi: 'अर्जुन की विषाद',
    description: 'The yoga of Arjuna\'s dejection. Arjuna sees his relatives on the battlefield and is overwhelmed with despair.',
    theme: 'Despair and Confusion',
    yogaType: 'Vishada Yoga',
    verseCount: 47,
    duration: '15:30',
    color: 'from-slate-500 to-gray-600',
    verses: [],
  },
  {
    number: 2,
    nameSanskrit: 'सांख्ययोग',
    nameEnglish: 'Sankhya Yoga',
    nameHindi: 'सांख्य योग',
    description: 'The yoga of knowledge. Krishna teaches the nature of the soul and the importance of duty.',
    theme: 'Knowledge and Duty',
    yogaType: 'Jnana Yoga',
    verseCount: 72,
    duration: '25:00',
    color: 'from-amber-500 to-orange-600',
    verses: [],
  },
  {
    number: 3,
    nameSanskrit: 'कर्मयोग',
    nameEnglish: 'Karma Yoga',
    nameHindi: 'कर्म योग',
    description: 'The yoga of action. Krishna explains selfless action as a path to liberation.',
    theme: 'Selfless Action',
    yogaType: 'Karma Yoga',
    verseCount: 43,
    duration: '18:00',
    color: 'from-[#d4a44c] to-red-600',
    verses: [],
  },
  {
    number: 4,
    nameSanskrit: 'ज्ञानकर्मसंन्यासयोग',
    nameEnglish: 'Jnana Karma Sanyasa Yoga',
    nameHindi: 'ज्ञान कर्म संन्यास योग',
    description: 'The yoga of renunciation of action through knowledge.',
    theme: 'Divine Knowledge',
    yogaType: 'Jnana Yoga',
    verseCount: 42,
    duration: '17:30',
    color: 'from-yellow-500 to-amber-600',
    verses: [],
  },
  {
    number: 5,
    nameSanskrit: 'कर्मसंन्यासयोग',
    nameEnglish: 'Karma Sanyasa Yoga',
    nameHindi: 'कर्म संन्यास योग',
    description: 'The yoga of renunciation of action. Harmonizing action and renunciation.',
    theme: 'Renunciation',
    yogaType: 'Karma Yoga',
    verseCount: 29,
    duration: '12:00',
    color: 'from-lime-500 to-green-600',
    verses: [],
  },
  {
    number: 6,
    nameSanskrit: 'आत्मसंयमयोग',
    nameEnglish: 'Atma Samyama Yoga',
    nameHindi: 'आत्म संयम योग',
    description: 'The yoga of self-control. Meditation and the disciplined mind.',
    theme: 'Meditation',
    yogaType: 'Dhyana Yoga',
    verseCount: 47,
    duration: '20:00',
    color: 'from-emerald-500 to-teal-600',
    verses: [],
  },
  {
    number: 7,
    nameSanskrit: 'ज्ञानविज्ञानयोग',
    nameEnglish: 'Jnana Vijnana Yoga',
    nameHindi: 'ज्ञान विज्ञान योग',
    description: 'The yoga of knowledge and wisdom. Understanding the divine nature.',
    theme: 'Divine Wisdom',
    yogaType: 'Jnana Yoga',
    verseCount: 30,
    duration: '13:00',
    color: 'from-cyan-500 to-blue-600',
    verses: [],
  },
  {
    number: 8,
    nameSanskrit: 'अक्षरब्रह्मयोग',
    nameEnglish: 'Akshara Brahma Yoga',
    nameHindi: 'अक्षर ब्रह्म योग',
    description: 'The yoga of the imperishable Brahman. The path to the eternal.',
    theme: 'The Eternal',
    yogaType: 'Brahma Yoga',
    verseCount: 28,
    duration: '12:30',
    color: 'from-blue-500 to-indigo-600',
    verses: [],
  },
  {
    number: 9,
    nameSanskrit: 'राजविद्याराजगुह्ययोग',
    nameEnglish: 'Raja Vidya Raja Guhya Yoga',
    nameHindi: 'राज विद्या राज गुह्य योग',
    description: 'The yoga of royal knowledge and the royal secret.',
    theme: 'Royal Knowledge',
    yogaType: 'Bhakti Yoga',
    verseCount: 34,
    duration: '15:00',
    color: 'from-indigo-500 to-purple-600',
    verses: [],
  },
  {
    number: 10,
    nameSanskrit: 'विभूतियोग',
    nameEnglish: 'Vibhuti Yoga',
    nameHindi: 'विभूति योग',
    description: 'The yoga of divine glories. Krishna reveals his divine manifestations.',
    theme: 'Divine Glory',
    yogaType: 'Vibhuti Yoga',
    verseCount: 42,
    duration: '18:00',
    color: 'from-violet-500 to-purple-600',
    verses: [],
  },
  {
    number: 11,
    nameSanskrit: 'विश्वरूपदर्शनयोग',
    nameEnglish: 'Vishvarupa Darshana Yoga',
    nameHindi: 'विश्वरूप दर्शन योग',
    description: 'The yoga of the vision of the cosmic form. Arjuna sees Krishna\'s universal form.',
    theme: 'Cosmic Vision',
    yogaType: 'Darshana Yoga',
    verseCount: 55,
    duration: '22:00',
    color: 'from-purple-500 to-pink-600',
    verses: [],
  },
  {
    number: 12,
    nameSanskrit: 'भक्तियोग',
    nameEnglish: 'Bhakti Yoga',
    nameHindi: 'भक्ति योग',
    description: 'The yoga of devotion. The path of loving devotion to God.',
    theme: 'Devotion',
    yogaType: 'Bhakti Yoga',
    verseCount: 20,
    duration: '10:00',
    color: 'from-pink-500 to-rose-600',
    verses: [],
  },
  {
    number: 13,
    nameSanskrit: 'क्षेत्रक्षेत्रज्ञविभागयोग',
    nameEnglish: 'Kshetra Kshetrajna Vibhaga Yoga',
    nameHindi: 'क्षेत्र क्षेत्रज्ञ विभाग योग',
    description: 'The yoga of the distinction between the field and the knower.',
    theme: 'Field and Knower',
    yogaType: 'Jnana Yoga',
    verseCount: 35,
    duration: '14:00',
    color: 'from-rose-500 to-red-600',
    verses: [],
  },
  {
    number: 14,
    nameSanskrit: 'गुणत्रयविभागयोग',
    nameEnglish: 'Gunatraya Vibhaga Yoga',
    nameHindi: 'गुण त्रय विभाग योग',
    description: 'The yoga of the division of three gunas. Understanding the three qualities of nature.',
    theme: 'Three Gunas',
    yogaType: 'Guna Yoga',
    verseCount: 27,
    duration: '11:30',
    color: 'from-red-500 to-orange-600',
    verses: [],
  },
  {
    number: 15,
    nameSanskrit: 'पुरुषोत्तमयोग',
    nameEnglish: 'Purushottama Yoga',
    nameHindi: 'पुरुषोत्तम योग',
    description: 'The yoga of the supreme person. The eternal tree and the supreme being.',
    theme: 'Supreme Being',
    yogaType: 'Purushottama Yoga',
    verseCount: 20,
    duration: '9:00',
    color: 'from-amber-500 to-yellow-600',
    verses: [],
  },
  {
    number: 16,
    nameSanskrit: 'दैवासुरसंपद्विभागयोग',
    nameEnglish: 'Daivasura Sampad Vibhaga Yoga',
    nameHindi: 'दैवासुर संपद् विभाग योग',
    description: 'The yoga of the division between divine and demonic qualities.',
    theme: 'Divine vs Demonic',
    yogaType: 'Vibhaga Yoga',
    verseCount: 24,
    duration: '10:30',
    color: 'from-teal-500 to-cyan-600',
    verses: [],
  },
  {
    number: 17,
    nameSanskrit: 'श्रद्धात्रयविभागयोग',
    nameEnglish: 'Shraddhatraya Vibhaga Yoga',
    nameHindi: 'श्रद्धा त्रय विभाग योग',
    description: 'The yoga of the threefold division of faith.',
    theme: 'Threefold Faith',
    yogaType: 'Shraddha Yoga',
    verseCount: 28,
    duration: '12:00',
    color: 'from-green-500 to-emerald-600',
    verses: [],
  },
  {
    number: 18,
    nameSanskrit: 'मोक्षसंन्यासयोग',
    nameEnglish: 'Moksha Sanyasa Yoga',
    nameHindi: 'मोक्ष संन्यास योग',
    description: 'The yoga of liberation through renunciation. The final teaching and surrender.',
    theme: 'Liberation',
    yogaType: 'Moksha Yoga',
    verseCount: 78,
    duration: '30:00',
    color: 'from-fuchsia-500 to-purple-600',
    verses: [],
  },
]

// ============ Default Learning Settings ============

export const DEFAULT_LEARNING_SETTINGS: GitaLearningSettings = {
  showTransliteration: true,
  showMeaning: true,
  showCommentary: false,
  playbackSpeed: 1.0,
  pauseDuration: 3,
  autoAdvance: true,
}

// ============ Gita Soundscapes ============

export const GITA_SOUNDSCAPES: GitaSoundscape[] = [
  {
    id: 'morning-meditation',
    name: 'Morning Meditation',
    nameHindi: 'प्रातः ध्यान',
    description: 'Start your day with peaceful Gita verses and gentle morning sounds.',
    icon: 'Sun',
    gradient: 'from-amber-500 to-orange-600',
    theme: 'Morning',
    recommendedTime: 'Early Morning',
    benefits: ['Mental Clarity', 'Positive Start', 'Inner Peace'],
    ambientSounds: ['birds', 'bells', 'wind'],
  },
  {
    id: 'night-reflection',
    name: 'Night Reflection',
    nameHindi: 'रात्रि चिंतन',
    description: 'End your day with calming verses and soothing night sounds.',
    icon: 'Moon',
    gradient: 'from-indigo-500 to-purple-600',
    theme: 'Night',
    recommendedTime: 'Before Sleep',
    benefits: ['Better Sleep', 'Stress Relief', 'Peace of Mind'],
    ambientSounds: ['crickets', 'wind', 'soft-music'],
  },
  {
    id: 'focus-study',
    name: 'Focus & Study',
    nameHindi: 'एकाग्रता',
    description: 'Enhance concentration with verses on focus and ambient study sounds.',
    icon: 'Brain',
    gradient: 'from-cyan-500 to-blue-600',
    theme: 'Focus',
    recommendedTime: 'Study Hours',
    benefits: ['Concentration', 'Memory', 'Learning'],
    ambientSounds: ['rain', 'soft-music', 'binaural'],
  },
  {
    id: 'heart-devotion',
    name: 'Heart Devotion',
    nameHindi: 'भक्ति',
    description: 'Connect with divine love through bhakti verses and devotional sounds.',
    icon: 'Heart',
    gradient: 'from-pink-500 to-rose-600',
    theme: 'Devotion',
    recommendedTime: 'Anytime',
    benefits: ['Divine Connection', 'Love', 'Surrender'],
    ambientSounds: ['flute', 'bells', 'chanting'],
  },
  {
    id: 'wisdom-insight',
    name: 'Wisdom & Insight',
    nameHindi: 'ज्ञान',
    description: 'Deep philosophical verses for contemplation and understanding.',
    icon: 'BookOpen',
    gradient: 'from-violet-500 to-purple-600',
    theme: 'Wisdom',
    recommendedTime: 'Quiet Hours',
    benefits: ['Understanding', 'Clarity', 'Self-Knowledge'],
    ambientSounds: ['temple', 'wind', 'bells'],
  },
  {
    id: 'divine-energy',
    name: 'Divine Energy',
    nameHindi: 'दैवी शक्ति',
    description: 'Energizing verses with powerful ambient sounds for motivation.',
    icon: 'Sparkles',
    gradient: 'from-yellow-500 to-amber-600',
    theme: 'Energy',
    recommendedTime: 'Morning/Afternoon',
    benefits: ['Motivation', 'Strength', 'Courage'],
    ambientSounds: ['drums', 'chanting', 'nature'],
  },
]

export default {
  GITA_CHAPTERS,
  DEFAULT_LEARNING_SETTINGS,
  GITA_SOUNDSCAPES,
}
