name: Secret scan (simple)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Grep for private key patterns
        run: |
          set -e
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD || true)
          if [ -z "$CHANGED_FILES" ]; then
            CHANGED_FILES=$(git ls-files)
          fi
          FOUND=""
          for f in $CHANGED_FILES; do
            if file "$f" 2>/dev/null | grep -qi 'text'; then
              MATCH=$(grep -En --line-number -I -e '-----BEGIN (RSA |EC |DSA |PRIVATE |)KEY-----' -e '"private_key"' -e 'PRIVATE_KEY' -e 'SECRET_KEY' -e 'AWS_SECRET_ACCESS_KEY' -e '-----BEGIN OPENSSH PRIVATE KEY-----' "$f" || true)
              if [ -n "$MATCH" ]; then
                FOUND="$FOUND\n$f:$MATCH"
              fi
            fi
          done
          if [ -n "$FOUND" ]; then
            echo "Potential private key or secret patterns found in changed files:"
            echo -e "$FOUND"
            echo "Failing the check. Please remove secrets and use repository secrets."
            exit 1
          fi
      - name: Advice
        run: echo "Consider enabling GitHub secret scanning & advanced scanners in repo settings"
