name: Upload runtime diagnostics

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - fix/upload-artifacts

jobs:
  collect-and-upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug: show workspace & runner temp (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "RUNNER_TEMP: $RUNNER_TEMP"

      - name: Debug: show workspace & runner temp (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Write-Host "GITHUB_WORKSPACE: $Env:GITHUB_WORKSPACE"
          Write-Host "RUNNER_TEMP: $Env:RUNNER_TEMP"

      - name: Collect runtime logs (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          set -euo pipefail
          chmod +x ./scripts/collect-runtime-logs.sh || true
          ./scripts/collect-runtime-logs.sh

      - name: Collect runtime logs (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          ./scripts/collect-runtime-logs.ps1

      - name: Upload runtime-logs artifact (warn if nothing found)
        uses: actions/upload-artifact@v4
        with:
          name: runtime-logs
          path: ${{ runner.temp }}/runtime-logs/**
          if-no-files-found: 'warn'
